### ISSUE TITLE
`multiple definition of tab` linking error

### ISSUE THREAD

**Issue by ajusa** [yglukhov/iface#11]
Hello,

```nim
# faces.nim
import iface
iface *Animal: # Define the interface
  proc say(): string
type
  Dog = ref object of RootRef # The Dog doesn't explicitly inherit Animal

proc say(a: Dog): string = "default message"
proc doSmth*(a: Animal): string = a.say() # Here we're working with an animal
echo Dog().doSmth()
import twoface
Cat().other()

# twoface.nim
import faces
type Cat* = ref object
proc say*(c: Cat): string = "meow"
proc other*(c: Cat) = echo c.doSmth()
```
When trying to compile the above MWE, I get
```
/usr/bin/ld: /home/ajusa/.cache/nim/faces_d/@mfaces.nim.c.o:(.bss+0x80): multiple definition of `tab__MvkRb79c9cByhV0K9a5bmpgKg'; /home/ajusa/.cache/nim/faces_d/@mtwoface.nim.c.o:(.bss+0x80): first defined here
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o /home/ajusa/.cache/nim/faces_d/faces  /home/ajusa/.cache/nim/faces_d/stdlib_io.nim.c.o /home/ajusa/.cache/nim/faces_d/stdlib_system.nim.c.o /home/ajusa/.cache/nim/faces_d/@m..@s..@s.nimble@spkgs@siface-0.1.0@siface.nim.c.o /home/ajusa/.cache/nim/faces_d/@mtwoface.nim.c.o /home/ajusa/.cache/nim/faces_d/@mfaces.nim.c.o  -lm   -ldl'
```

The expected behavior is that I see "default message" and then "meow" print. Not really sure why this is happening though, I've never ran into a linker error with just Nim code. Let me know if you need more information or if you can't reproduce!

**Comment by ajusa** [comment]
After doing some more debugging, it seems that the linker error is caused by gcc 10, see first item under https://gcc.gnu.org/gcc-10/porting_to.html

I was able to get it to go away by adding the `-fcommon` flag to passC, but ideally this could be solved in a gcc version agnostic way. Now, the error that I get is
```
default message
/home/ajusa/Documents/tmp/faces.nim(11) faces
/home/ajusa/Documents/tmp/twoface.nim(5) other
/home/ajusa/Documents/tmp/faces.nim(8) doSmth
/home/ajusa/.nimble/pkgs/iface-#head/iface.nim(21) :anonymous
/home/ajusa/.choosenim/toolchains/nim-1.4.4/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: invalid object conversion [ObjectConversionDefect]
Error: execution of an external program failed: '/home/ajusa/.cache/nim/faces_d/faces '
```
which happens at runtime. Line 21 has
```nim
template unpackObj[T](f: RootRef, res: var T) =
  when T is RootRef:
    res = T(f)
  else:
    res = CTWrapper[T](f).v
```
Not really sure why this is an invalid thing to do - I make a Cat which implements Animal, call a function that takes in a Cat, which calls a function that takes an Animal, which finally should call the implemented function `say` and echo "meow".

**Comment by ajusa** [comment]
Huh, got it to work on devel seems like, must be a compiler bug that was fixed. Leaving this issue open to deal with the gcc9/10 stuff though.

**Comment by yglukhov** [comment]
I could reproduce the gcc bug with nim 1.4.*, but not with devel, so I believe that one is fixed in nim too.
