### ISSUE TITLE
"Object does not implement required ..." when returning interface type in an expression with noreturn branches

### ISSUE THREAD

**Issue by ghost** [yglukhov/iface#7]
Code to trigger an error:

```nim
import iface

iface Mapper:
  proc step()

type
  Mapper1 = ref object of RootObj
  Mapper2 = ref object of RootObj

proc step(m: Mapper1) = discard
proc step(m: Mapper2) = discard

proc res(x: int): Mapper = 
  result = case x
  of 1: Mapper1()
  of 2: Mapper2()
  else: raise newException(ValueError, "error!")

let test = res(3)
```

I'm not sure if this is supposed to be supported though :)
Can be easily worked around by doing "result = " assignments in each case branch.

**Comment by yglukhov** [comment]
Indeed, i guess the problem here is that the type of the case expression is `RootRef` and not `Mapper1` or `Mapper2`. And the error happens because `step` is not implemented for `RootRef`. Not sure if this can be mitigated.

**Comment by yglukhov** [comment]
Another workaround should be:
```nim
proc res(x: int): Mapper = 
  result = case x
  of 1: Mapper(Mapper1())
  of 2: Mapper(Mapper2())
  else: raise newException(ValueError, "error!")
```

**Comment by yglukhov** [comment]
Yeah I believe there's nothing we can do about it.
