### ISSUE TITLE
explicit matching of interface

### ISSUE THREAD

**Issue by kobi2187** [yglukhov/iface#9]
Hi!
What do you think about this feature request
add a hidden field to the interface,
iface Animal
matchesAnimalInterface:bool # hidden field, created through the macro.
type A = ref object
with a little more syntax: match A to Animal
will create a field in type A called, you guessed it, matchesAnimalInterface:bool
so the user is not aware, but examining the type shows something intelligible and not some obfuscated weird chars.
What this allows: ability to "tag" a type as belonging to this interface, 
for example, I want to specify that my proc will only accept certain types, but they don't specifically have anything in common. They can be common to a few groups.
think of the Animal sequence we talked about, for example. you want to add a few animals, but don't want to specify a trait. This is basically the usecase. (In reality my use case is something like language constructs, for a compiler, where the common thing is a "gen" method but other unrelated constructs have it too.)

**Comment by yglukhov** [comment]
I'm not sure I understand the problem. If you want to tag a type as belonging to an interface, why do you need a feature in `iface` for that? Also what does the tagging give? The type either implements the interface or doesn't, which I believe you can check in compile time like `compiles(Animal(myValue))`. Maybe a more complete snippet of code would explain your intent better? If any, please format it properly in backticks to not make my eyes bleed.

**Comment by kobi2187** [comment]
with nominal typing, a type relies on the naming to "belong" to a certain interface. it is declared as such.
with structural typing, there is a benefit that you don't have to touch the original type, which is sometimes beyond your control anyway. But you do want this sometimes: an empty interface. Just to combine a few types together, whether in a design stage for rapid prototyping (with the compiler later letting you know you missed an implementation), or in order to limit certain types from working with your proc, when you rely on dynamic dispatch in object oriented code.

**Comment by yglukhov** [comment]
Well there's a theory behind it, I get it. But I don't understand what specific operations/semantics you'd want to achieve in nim. Adding a field to a type by using `matches(Animal)` syntax instead of `matchesAnimal: bool` doesn't change anything except the syntax, does it?

**Comment by kobi2187** [comment]
yes, i added a field to the interface: `proc matchesAnimal():bool`
and then 
`proc matchesAnimal*(this:TypeA|TypeB|TypeC|TypeD) = true`
so in practice, I discovered it's a one-liner and doesn't really need special syntax.
